In [37]:
import numpy as np


In [38]:
print(np.__version__)
np.show_config()


1.16.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [39]:
zeros = np.zeros(10)
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
Z = np.zeros((10, 10))
print(f'{Z.size * Z.itemsize} bytes')


800 bytes


In [41]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [42]:
Z = np.zeros(10)
Z[4] = 1
print(Z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [43]:
Z = np.arange(10, 50)
print(Z)



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [44]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)


[9 8 7 6 5 4 3 2 1 0]


In [45]:
Z = np.arange(9).reshape(3, 3)
print(Z)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
not_zeros = np.nonzero([1,2,0,0,4,0])
print(not_zeros)


(array([0, 1, 4]),)


In [47]:
Z = np.eye(3)
print(Z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
Z = np.random.random((3, 3, 3))
print(Z)


[[[0.32436708 0.150793   0.33827589]
  [0.60187118 0.00820321 0.17383147]
  [0.0909839  0.96577934 0.04381173]]

 [[0.86286614 0.96228365 0.91034651]
  [0.66928279 0.00963844 0.50826855]
  [0.5254485  0.15540583 0.72953023]]

 [[0.91883134 0.99914217 0.01197185]
  [0.28338917 0.3927763  0.16727936]
  [0.4160838  0.98161974 0.5622497 ]]]


In [49]:
Z = np.random.random((10, 10))
z_min, z_max = Z.min(), Z.max()
print(z_max, z_min)


0.9822049065043443 0.00036468882059992325


In [50]:
Z = np.random.random(30)
m = Z.mean()
print(m)


0.41163539954963574


In [51]:
Z = np.ones((10, 10))
Z[1:-1, 1:-1] = 0
print(Z)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [52]:
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [53]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


In [54]:
Z = np.diag(1+np.arange(4), k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [55]:
Z = np.zeros((8, 8), dtype=int)
Z[1::2, ::2] = 1
Z[::2, 1::2] = 1
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [56]:
print(np.unravel_index(100, (6, 7, 8)))


(1, 5, 4)


In [57]:
Z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [58]:
Z = np.random.random((5, 5))
z_max, z_min = Z.max(), Z.min()
Z = (Z - z_min) / (z_max - z_min)
print(Z)


[[0.78255621 0.25370401 0.73975914 0.62050113 0.5863612 ]
 [0.74337383 0.39842937 1.         0.65343565 0.87001852]
 [0.18253887 0.97698924 0.17111691 0.78757594 0.70790798]
 [0.40725501 0.73426495 0.         0.17323795 0.60012004]
 [0.03725938 0.39717284 0.60695674 0.09192654 0.3304011 ]]


In [59]:
color = np.dtype(
    [
        ("r", np.ubyte, 1),
        ("g", np.ubyte, 1),
        ("b", np.ubyte, 1),
        ("a", np.ubyte, 1)
    ]
)
color
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [60]:
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [61]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [62]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [63]:
Z = np.arange(5)
Z**Z
# 2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z


array([0., 1., 2., 3., 4.])

In [64]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/Users/skhe/.local/share/virtualenvs/data_analysis-q7BnlpsL/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/skhe/.local/share/virtualenvs/data_analysis-q7BnlpsL/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [65]:
Z = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[  6.  -8.  -2.   6.   8.   7. -10.  -9.  -2.  -3.]


In [66]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print(np.intersect1d(Z1, Z2))


[0 2 3 4]


In [67]:
with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0


In [68]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/skhe/.local/share/virtualenvs/data_analysis-q7BnlpsL/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [69]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow, sep='\n')


2019-06-22
2019-06-23
2019-06-24


In [70]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [47]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

In [71]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(Z.astype(int))
print(np.trunc(Z))

[2. 9. 0. 6. 7. 0. 6. 7. 0. 3.]
[2. 9. 0. 6. 7. 0. 6. 7. 0. 3.]
[2. 9. 0. 6. 7. 0. 6. 7. 0. 3.]
[2 9 0 6 7 0 6 7 0 3]
[2. 9. 0. 6. 7. 0. 6. 7. 0. 3.]


In [72]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [73]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [74]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [75]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.01073808 0.09046072 0.1129918  0.3168608  0.40529274 0.42233175
 0.43326672 0.59415286 0.83851743 0.93628046]


In [76]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [77]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [78]:
Z = np.zeros(10)
Z.flags.writeable = False

In [79]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print (R)
print (T)

[1.0193503  0.78393633 0.49882252 1.33578644 0.97004896 0.87451564
 1.12226442 0.8924998  0.73727305 0.97567873]
[0.64339718 0.24996085 1.10453919 0.76210008 0.7652886  0.13627144
 0.51640334 0.36629668 0.24333383 0.27414542]


In [80]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print (Z)

[0.52012949 0.68197003 0.00996888 0.49158167 0.49251823 0.57661105
 0.39209333 0.00777998 0.28684042 0.        ]


In [81]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [82]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [83]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [85]:
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [86]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

60


In [87]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [88]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.73875172 0.74712681 0.84883813 1.12139616 0.35896476
  0.0351482  0.35693508 0.80190025 0.16525498]
 [0.73875172 0.         0.72804363 0.55199249 0.68426491 0.43808538
  0.75148459 0.4441764  0.58744619 0.66382291]
 [0.74712681 0.72804363 0.         0.27847377 0.51581666 0.49334399
  0.7816181  0.79484774 0.19749192 0.83253977]
 [0.84883813 0.55199249 0.27847377 0.         0.27946015 0.51188293
  0.87942756 0.77226469 0.08179967 0.88460265]
 [1.12139616 0.68426491 0.51581666 0.27946015 0.         0.77357112
  1.15079937 1.00361327 0.34759369 1.14337824]
 [0.35896476 0.43808538 0.49334399 0.51188293 0.77357112 0.
  0.38440038 0.30264231 0.48093714 0.37272122]
 [0.0351482  0.75148459 0.7816181  0.87942756 1.15079937 0.38440038
  0.         0.35525631 0.83377906 0.14670735]
 [0.35693508 0.4441764  0.79484774 0.77226469 1.00361327 0.30264231
  0.35525631 0.         0.75885261 0.23294472]
 [0.80190025 0.58744619 0.19749192 0.08179967 0.34759369 0.48093714
  0.83377906 0.75885

In [89]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [91]:
from io import StringIO
s = StringIO("1, 2, 3, 4, 5, 6,  ,  , 7, 8, ,  , 9,10,11")
data = np.genfromtxt(s, delimiter=',')
print(data)

[ 1.  2.  3.  4.  5.  6. nan nan  7.  8. nan nan  9. 10. 11.]


In [92]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [93]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [94]:
 n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [95]:
X = np.random.rand(5, 10)
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.27800722 -0.15663917  0.01641383 -0.1263853   0.1065538   0.15773753
   0.15694243  0.40134415  0.02028355 -0.29824358]
 [-0.09031395  0.47846022  0.36649233 -0.35600608 -0.28830331 -0.05871033
  -0.34517595  0.57192125 -0.23021537 -0.04814881]
 [-0.33521102 -0.23321484 -0.12585194 -0.24986669  0.45056013 -0.38830046
   0.21444932 -0.03551816  0.21746585  0.48548781]
 [-0.02169451 -0.19802041 -0.12882435 -0.31252492  0.47396037  0.05781416
  -0.33902943  0.49561458 -0.10273731  0.07544181]
 [-0.05963719 -0.27405893 -0.40736718  0.22429467  0.19705397  0.4194325
  -0.07018885 -0.22197585  0.32084196 -0.12839509]]


In [96]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[6 5 0]
 [3 2 7]
 [4 2 6]]
[[3 2 7]
 [4 2 6]
 [6 5 0]]


In [97]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


In [98]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.4800664687210491


In [99]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [100]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [101]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 6. 2. 2. 4. 3. 2. 3. 2. 3.]


In [102]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [103]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


In [104]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print (sum)

[[39 51 47 55]
 [65 59 51 64]
 [60 51 49 59]]


In [105]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.41314931 0.48089429 0.47238221 0.5309016  0.66026866 0.49353887
 0.42347887 0.73204943 0.44250345 0.44062943]


In [106]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
# slow version
np.diag(np.dot(A, B))

array([1.17670668, 1.59260095, 1.7790436 , 0.48161108, 1.51935317])

In [107]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [108]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [109]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [110]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[( 2, 46) ( 2, 54) ( 5, 48) ( 5, 59) ( 6, 68) ( 6, 73) (11, 78) (11, 96)
 (17, 18) (17, 46) (18, 46) (21, 23) (21, 92) (22, 51) (22, 84) (22, 96)
 (23, 92) (28, 31) (28, 33) (31, 33) (46, 54) (48, 59) (51, 84) (51, 96)
 (68, 73) (68, 80) (68, 82) (78, 96) (80, 82)]


In [111]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


In [112]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [113]:
 from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [114]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

In [115]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[15.28151345  2.10033094  5.05632876  8.63418     1.70093457 12.51389173
  8.08645726  3.68476831  5.33462444 13.81500924]


In [116]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.45861941  9.59201441  7.62904207  7.85389838  1.43917003  1.17764658
   3.02223542  1.46800952  2.43034129  7.46849308]
 [10.19282962  0.04302982  3.8661976   2.70542861  8.07693298  3.10581452
   0.61573571 11.82082535  2.53795749  0.08014063]
 [ 8.82932327  2.26341473 11.46410153  2.5152851  10.43452751  9.63185685
   7.40154465  8.8310494   5.13588041  4.62450323]
 [ 0.68116599  5.81398862 15.7287562   6.76524809  2.39245239  6.70678783
   5.07534632  0.6244484   6.20600055  1.41481599]
 [ 6.42096745  4.79114492  2.4426929   1.48366842  3.32228244  1.15082086
   3.48092257  8.79934686  5.46646371  4.72715347]
 [15.13088172  5.38692544  4.14439626  7.93092979 13.50498635  7.10241768
   4.36343542 16.1473238   0.41060226  5.14603401]
 [14.41426056  5.42298702  5.76583898  7.4438492  13.55228579  8.17446579
   5.5129708  15.13075054  1.06948811  5.69774095]
 [ 6.76914629  3.69114174  3.90849272  0.87916311  4.431691    0.56865772
   1.74299566  8.76613994  3.75975892  3.25006101]


In [117]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[8 1 3 9 3 8 0 5 1 9]
 [6 8 8 4 0 1 3 1 3 6]
 [8 6 3 1 2 3 2 7 9 4]
 [5 2 9 1 2 5 5 1 3 5]
 [2 5 8 4 5 7 1 4 9 6]
 [8 6 4 8 0 0 5 7 7 7]
 [4 7 9 7 4 6 2 8 2 6]
 [5 0 2 9 5 3 9 0 7 6]
 [5 6 3 6 9 4 0 8 7 7]
 [1 8 4 0 1 9 8 0 8 1]]
[[0 0 0 0 0]
 [0 8 1 3 9]
 [0 6 8 8 4]
 [0 8 6 3 1]
 [0 5 2 9 1]]


/Users/skhe/.local/share/virtualenvs/data_analysis-q7BnlpsL/lib/python3.7/site-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [118]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [119]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


In [120]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

1


In [121]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[4 2 3]
   [1 0 0]
   [0 2 2]]

  [[2 3 0]
   [0 0 2]
   [2 2 2]]

  [[3 0 4]
   [0 2 0]
   [2 2 4]]

  [[0 4 3]
   [2 0 4]
   [2 4 4]]

  [[4 3 4]
   [0 4 2]
   [4 4 1]]

  [[3 4 0]
   [4 2 3]
   [4 1 4]]

  [[4 0 4]
   [2 3 4]
   [1 4 2]]

  [[0 4 2]
   [3 4 2]
   [4 2 0]]]


 [[[1 0 0]
   [0 2 2]
   [0 1 4]]

  [[0 0 2]
   [2 2 2]
   [1 4 3]]

  [[0 2 0]
   [2 2 4]
   [4 3 1]]

  [[2 0 4]
   [2 4 4]
   [3 1 1]]

  [[0 4 2]
   [4 4 1]
   [1 1 4]]

  [[4 2 3]
   [4 1 4]
   [1 4 3]]

  [[2 3 4]
   [1 4 2]
   [4 3 4]]

  [[3 4 2]
   [4 2 0]
   [3 4 4]]]


 [[[0 2 2]
   [0 1 4]
   [3 4 2]]

  [[2 2 2]
   [1 4 3]
   [4 2 4]]

  [[2 2 4]
   [4 3 1]
   [2 4 1]]

  [[2 4 4]
   [3 1 1]
   [4 1 4]]

  [[4 4 1]
   [1 1 4]
   [1 4 1]]

  [[4 1 4]
   [1 4 3]
   [4 1 1]]

  [[1 4 2]
   [4 3 4]
   [1 1 4]]

  [[4 2 0]
   [3 4 4]
   [1 4 1]]]


 [[[0 1 4]
   [3 4 2]
   [0 4 1]]

  [[1 4 3]
   [4 2 4]
   [4 1 3]]

  [[4 3 1]
   [2 4 1]
   [1 3 1]]

  [[3 1 1]
   [4 1 4]
   [3 1 2]]

  [[1 1 4]
   

In [122]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 2 14 16  4  5]
 [14  5 10  9  6]
 [16 10  4 42  6]
 [ 4  9 42  3 14]
 [ 5  6  6 14  1]]


In [123]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [124]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [125]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [126]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [127]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [128]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [129]:
x = np.random.rand()
np.power(x,3)

0.028737229689599707

In [130]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[0 2 5 7]


In [131]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[2 4 0]
 [1 0 4]
 [1 4 3]
 [4 2 0]
 [2 3 3]
 [2 3 2]
 [2 1 0]
 [0 3 1]
 [1 4 4]
 [1 0 0]]
[[2 4 0]
 [1 0 4]
 [1 4 3]
 [4 2 0]
 [2 3 3]
 [2 3 2]
 [2 1 0]
 [0 3 1]
 [1 4 4]
 [1 0 0]]


In [132]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [133]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 1 0]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [134]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)

sum
6.460971037391394


In [135]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [136]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [137]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.23505113  0.17223808]
